version: 2
plan:
  project-key: BASH
  key: PLAN
  name: My Plan

stages:
  - Stage 1:
      jobs:
        - Job1
        - Job2
Job1:
  tasks:
    - script:
        - echo 'Hello from YAML Specs'
Job2:
  tasks:
    - script: 
        interpreter: /bin/sh
        scripts:
          - env
