version: 2
plan:
  project-key: BASH
  key: PLAN
  name: My Plan

stages:
  - Stage1:
      jobs:
        - Job1
        - Job2
  - Stage2:
      jobs:
        - Job3
Job1:
  tasks:
    - script:
        - echo 'Hello from YAML Specs'
Job2:
  tasks:
    - script: 
        interpreter: /bin/sh
        scripts:
          - env
Job3:
  tasks:
    - script: 
        interpreter: /bin/sh
        scripts:
          - pwd
          - ls -al
          - env
